# default configuration

baseURL = "/"
title   = "Hugo Theme: hugo-pure"

languageCode   = "en-us"
hasCJKLanguage = true

[markup]
_merge    = "deep"
[markup.highlight]
_merge    = "deep"
noClasses = false
[markup.tableOfContents]
_merge    = "deep"
endLevel  = 2
    
[permalinks]
[permalinks.page]
v = "/:slugorfilename/"

#[params]
#doubleColumns = true
#showCorner = true

#[outputFormats]
#[outputFormats.myjson]
#baseName  = "myfilename"
#mediaType = "application/json"
#[outputs]
#home = ["html", "rss", "myjson"]
