# default configuration

baseURL             = "/"
title               = "Hugo Theme: hugo-pure"
hasCJKLanguage      = true
pluralizeListTitles = false
paginate            = 4

languageCode           = "en-us"
#defaultContentLanguage = 'en'

#[languages]
#[languages.en]
#languageCode = "en-us"
#languageName = "En"
#weight       = 1
#title        = "Hugo Theme: hugo-pure"

#[params]
#disableCornerIndicator = true

[markup]
_merge    = "deep"
[markup.highlight]
_merge    = "deep"
noClasses = false
    
[permalinks]
[permalinks.page]
v = "/:slugorfilename/"

[menus]
[[menus.main]]
identifier = "home"
pageRef    = "/"
name       = "Home"
weight     = 1

[[menus.footer]]
identifier = "copyright"
pageRef    = "/"
name       = "©2023"
weight     = 1

[[menus.footer]]
identifier = "rss"
pageRef    = "/index.xml"
name       = "RSS"
weight     = 3
[[menus.footer.params]]
targetBlank = true
iconClass   = "fa-solid fa-rss"

[[menus.footer]]
identifier = "search"
pageRef    = "/search"
name       = "Search"
weight     = 5
[[menus.footer.params]]
targetBlank = false
iconClass   = "fa-solid fa-magnifying-glass"

#[outputFormats]
#_merge    = "deep"
#[outputFormats.jsentries]
#_merge    = "deep"
#baseName  = "entries"
#mediaType = "text/javascript"

#[outputs]
#_merge    = "deep"
#home      = ["html", "rss", "jsentries"]
