# env: demo

defaultContentLanguage = 'en'

[languages]

[languages.en]
languageCode = "en-us"
languageName = "En"
weight = 1
title = "Hugo Theme: hugo-pure"

[languages.zh]
languageCode = "zh-cn"
languageName = "中"
weight = 3
title = "Hugo 主题: hugo-pure"

[params]
description = "Hugo theme: hugo-pure demo site"

[menus]

[[menus.main]]
identifier = "home_test"
url        = "/"
name      = "Home"
weight     = 1

[[menus.main]]
identifier = "tags_test"
url        = "/tags/"
name      = "Tags"
weight     = 9

[[menus.footer]]
identifier = "copyright"
url        = "/"
name      = "©2023"
weight     = 1

[[menus.footer]]
identifier= "rss"
url        = "/index.xml"
name      = "RSS"
weight     = 3
[[menus.footer.params]]
  targetBlank = true
  iconClass   = "fa-solid fa-rss"

[[menus.footer]]
identifier = "search"
url        = "/search/"
name      = "Search"
weight     = 5
[[menus.footer.params]]
  targetBlank = false
  iconClass   = "fa-solid fa-magnifying-glass"

[[menus.footer]]
identifier = "github"
url        = "https://github.com/undus5/hugo-pure"
name      = "Github"
weight     = 9
[[menus.footer.params]]
  targetBlank = true
  iconClass   = "fa-brands fa-github"
