# demo menus en

[[main]]
identifier = "home_demo"
pageRef = "/"
name = "Home"
weight = 1

[[main]]
identifier = "tags_demo"
pageRef    = "/tags/"
name       = "Tags"
weight     = 9

[[footer]]
identifier = "github"
url        = "https://github.com/undus5/hugo-pure"
name       = "Github"
weight     = 3
[[footer.params]]
targetBlank = true
iconClass   = "fa-brands fa-github"

[[footer]]
identifier = "rss"
pageRef    = "/"
name       = "RSS"
weight     = 5
[[footer.params]]
targetBlank = true
iconClass   = "fa-solid fa-rss"
format      = "rss"

